// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knrajfgtenlmcbjkihgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtucmFqZmd0ZW5sbWNiamtpaGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjUwODQsImV4cCI6MjA3NDQwMTA4NH0.CgJ4QzEzs6poC0KZOyfjuDG673xWK6wxZaeYKqSQQAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});